### ISSUE TITLE
[New Volunteer] <Tafadzwa Mqetu>

### ISSUE THREAD

**Issue by ttmqetu** [ACADEV1/.github#2]
Tafadzwa Mqetu

Projects: Google Maps Deprecation

Who have you talked to already?: Sammy Page

**Comment by sammypanda** [comment]
Hey @ttmqetu, adding you to the project now :)

the project repo is: https://github.com/ACADEV1/p036_Portal_Impact

i created an issue for this task: https://github.com/ACADEV1/p036_Portal_Impact/issues/12
